[Controls]
Style=Material

[Material]
#Dark  Light
Theme=Light
#ghostwhite  mintcream cadetblue
Primary=Indigo
#Dense Normal
Variant=Dense
#dodgerblue Teal   #E91E63
Accent=Blue
#Background = Grey
#Foreground = Brown

[Material\Font]
#Family=Noto Sans CJK SC
PixelSize=20