[Controls]
Style=Material

[Material]
#Dark  Light
Theme=Light
#ghostwhite  mintcream cadetblue
Primary=White
#Dense Normal
Variant=Normal
#dodgerblue Teal   #E91E63
#Accent=Teal
#Background = Grey
#Foreground = Brown

[Material\Font]
#Family=Noto Sans CJK SC
PixelSize=20